/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.jumlabs.jcr.oak.rpc.api.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum TTreeStatus implements org.apache.thrift.TEnum {
  UNCHANGED(0),
  NEW(1),
  MODIFIED(2);

  private final int value;

  private TTreeStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TTreeStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return UNCHANGED;
      case 1:
        return NEW;
      case 2:
        return MODIFIED;
      default:
        return null;
    }
  }
}
